name: Config Example
description: 'Config example form for Drupal deployment training.'
type: module
core_version_requirement: ^8.8 || ^9 || ^10
version: 1.0.0
package: Training
configure: config_example.admin_form
